[project]
name = "warp-mfem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imgui-bundle>=1.92.801",
    "newton>=1.1.0",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "pyarrow>=24.0.0",
    "pyglet>=2.1.14",
    "warp-lang>=1.12.1",
]
# Source - https://stackoverflow.com/a/79513219
# Posted by Moisés do Nascimento, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-30, License - CC BY-SA 4.0


[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.uv.workspace]
members = [
    "simkit",
]

[tool.uv.sources]
simkit = { workspace = true }
# Optional: force a specific import mode
#addopts = ["--import-mode=importlib"]


[dependency-groups]
dev = [
    "libigl>=2.6.2",
    "polyscope>=2.5.0",
    "pytest>=9.0.3",
    "scipy>=1.17.1",
    "torch>=2.12.0",
]
