[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mfem"]

[project]
name = "warp-mfem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imgui-bundle>=1.92.801",
    "libigl>=2.6.2",
    "matplotlib>=3.10.9",
    "newton[examples]>=1.1.0",
    "nvtx>=0.2.15",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "polyscope>=2.6.1",
    "pyarrow>=24.0.0",
    "pyglet>=2.1.14",
    "rerun-sdk>=0.33.1",
    "usd-core>=26.5",
    "viser>=1.0.30",
    "warp-lang>=1.12.1",
]
# Source - https://stackoverflow.com/a/79513219
# Posted by Moisés do Nascimento, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-30, License - CC BY-SA 4.0


[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "libigl>=2.6.2",
    "pytest>=9.0.3",
    "scipy>=1.17.1",
    "torch>=2.12.0",
]
